name: compile
on:
  push:
    branches: [ main ]
  pull_request:

env:
  GRADLE_OPTS: "-Xmx6g -Dorg.gradle.daemon=false"
  total-runners: 6

jobs:
  compile:
    runs-on: [self-hosted]
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Compile
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: false
          arguments: compileJava compileTestJava -Dorg.gradle.parallel=true
      - name: save classes
        uses: actions/upload-artifact@v3
        with:
          name: classes
          path: "**/*.class"
  compileJmh:
    runs-on: [self-hosted]
    needs: compile
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Restore classes
        uses: actions/download-artifact@v3
        with:
          name: classes
      - name: compileJmh
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileJmh
