# SPDX-License-Identifier: Apache-2.0
name: "Validate Gradle Wrapper"
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
