# SPDX-License-Identifier: Apache-2.0
name: "Validate Gradle Wrapper"
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: export runner UID
        run: echo "runner_uid=$UID" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ env.runner_uid }}
