# SPDX-License-Identifier: Apache-2.0
# Hyperledger Repolinter Action
name: Repolinter

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    runs-on: [ Linux ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: 'Run Repolinter'
        uses: newrelic/repolinter-action@v1
        with:
          config_url: https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/main/repo_structure/repolint.json
